### PR TITLE
Update stubbing matcher to consider regexs

### PR DESCRIPTION
**Pull request by gmassanek**

### CODE REVIEW

**Comment by cheald** [comment]
This'll need to test if the key is a regexp or string; the implementation as-is will match substrings, as well. For example:

    # Stub the home page
    client.stub("https://www.google.com/", body: "ok!")
    client.get("https://www.google.com/")
    # Then later, make a request for the search page
    client.get("https://www.google.com/search").body # => "ok!"

This will return the stubbed response, because 

    "https://www.google.com/search".match("https://www.google.com/") 
    #<MatchData "http://google.com/">

In the case that we path a string key, I think it should be considered only for exact matches; we could do this by building all keys as regexps and automatically anchoring anything passed as strings, or we could check the type of the key to determine what to do; this keeps the string case `O(1)` as well, rather than making it `O(n)` across the board.

**Comment by gmassanek** [comment]
I test drove that functionality out, but I think my expectations were wrong once I found that `Manticore::StubbedResponse` inherits from `Manticore::Response`.

Just pushed an update to coerce the incoming stub into a Regex when set/removed and an extra test.

**Comment by ebenoist** [comment]
+1 On getting this functionality into Manticore as it will likely allow for a similar PR against [Webmock](https://github.com/bblimke/webmock) to add manticore as one of the supported libraries. I'll dig in to see if there are any other gaps.

**Comment by cheald** [comment]
Looks good. I'm not crazy about the lookup being O(n) now, but I'm pretty sure n will be so small that it doesn't ever actually matter. :)

**Comment by gmassanek** [comment]
Yea, I wasn't too worried about the O(n) since it will only matter during tests. In production, I'd hope there are no registered stubs.

Thanks for pulling this in.

**Pull request merged**
