### PR TITLE
Better async error handling (catch some missing stuff

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes https://github.com/cheald/manticore/issues/22

### CODE REVIEW

**Comment by andrewvc** [comment]
Submitted a PR for this. One of the specs was tricky, @cheald any ideas?

**Comment by cheald** [comment]
I like the IllegalArgumentException handler (in general, Manticore should make an attempt to hide HTTPComponents exceptions as Ruby exceptions where reasonably appropriate), but I don't know if I want to wrap everything else via StandardError with a Manticore exception. The general idea behind that class of error is to consolidate all the network-related things that could go wrong into a single handleable error (ie, the opposite of what net/http does).

In the case of "everything else" we still need to pass it on to the failure handler, but I don't think I'd pass it on wrapped.

I'm going to go ahead and merge this and tweak the StandardError clause a bit.

**Comment by andrewvc** [comment]
@cheald I'm totally with you on unwrapping that stuff :)

**Comment by andrewvc** [comment]
BTW, thanks for the great client @cheald we're really glad to have it available.

**Comment by andrewvc** [comment]
BTW @cheald any chance this can get a point release to bump it? We have to do some weird stuff to handle these errors at the moment.

**Comment by cheald** [comment]
Yup, I'll do a new release once I polish this up!

**Comment by cheald** [comment]
Released 0.4.2. Thank you for the help!

**Comment by andrewvc** [comment]
Thanks @cheald ! If you're curious I'll be released two new gems sometime early next week (most likely Monday) based on this release:

https://github.com/logstash-plugins/logstash-input-http_poller
which in turn is based on
https://github.com/logstash-plugins/logstash-mixin-http_client
which in turn is based on Manticore

**Comment by cheald** [comment]
Oh, http_poller is super interesting; we have an immediate need for that in-house. I'll forward it on to my team! Thanks!

**Pull request merged**
