### PR TITLE
Fix example for truststore to use correct option.

### PR DESCRIPTION
**Pull request by andrewvc**
Also add `ca_file` example

This really confused me till I dug into the source.

### CODE REVIEW

**Comment by cheald** [comment]
Good call - how about just adding the `ca_certs` option to the `proxied_backend_client` declaration rather than defining a third client (since the doc is only talking about two clients there).

**Comment by andrewvc** [comment]
@cheald fixed!

**Comment by cheald** [comment]
Heh, let's leave the `truststore` and `truststore_password` options in there, too. Sorry!

**Comment by andrewvc** [comment]
@cheald can you specify both of them at the same time? I assume the client will check both stores?

By the way, thought you'd like to know we've decided to make manticore the preferred HTTP client for Logstash here at Elastic.

**Comment by cheald** [comment]
Oh, whoops, no, you're right. ca_store is the OpenSSL-compatible replacement for Java's truststore shenannigans. I think the best way to do that then would be to have two declarations there, one commented, like:

    # With an OpenSSL CA store
    proxied_backend_client = Manticore::Client.new proxy: "https://backend.internal:4242", ssl: {ca_file: "my_certs.pem"}
    # Or with a .jsk truststore
    # proxied_backend_client = Manticore::Client.new proxy: "https://backend.internal:4242", ssl: {truststore: "./truststore.jks", truststore_password: "s3cr3t"}

I'm glad to hear that you're finding it useful! We're big ES users, and have been really pleased with Manticore's performance WRT Elasticsearch in our stuff, as well. :)

**Comment by andrewvc** [comment]
@cheald updated!

**Comment by cheald** [comment]
Looks good, thanks!

**Pull request merged**
