### PR TITLE
Fix proxy to work when auth specified

### PR DESCRIPTION
**Pull request by andrewvc**
The code for using authorizations with proxies mistakenly assumes that all proxy usages are hashes. This lets that codepath handle strings as well.

This was spotted in the wild here: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/516

### CODE REVIEW

**Comment by andrewvc** [comment]
@cheald LMK if you think this needs new tests. This seems like a real bear to add functional tests for.

**Comment by andrewvc** [comment]
@cheald any update here?

**Comment by cheald** [comment]
So sorry, I've gotten distracted every time I've sat down to look at this. I've just pushed a branch with these changes plus specs to cover them; once it builds I'll merge. Thanks!

**Comment by andrewvc** [comment]
Thanks @cheald ! I really appreciate you writing the specs. It can be much harder to reason about mocking/stubbing in a project like this.

BTW, when do you think this will be released?

**Comment by cheald** [comment]
There are a couple of other open issues that I'd like to get to, but should cut a new release soon.

**Comment by andrewvc** [comment]
@cheald great, no rush, thank you!

**Pull request merged**
