### PR TITLE
Adds HttpDeleteWithEntity

### PR DESCRIPTION
**Pull request by hobodave**
Some REST APIs accept entity bodies for DELETE requests. This allows
the DELETE to have a body.

### CODE REVIEW

**Comment by hobodave** [comment]
If this looks good, any chance you could put out version 0.4.5 with this? Thanks!

**Comment by cheald** [comment]
Looks good. I'm going to actually update HttpGetWithEntity to have a similar implementation and am going to roll it into the 0.5.0 release. This release will update HTTPComponents to 4.5.x and changes the background request semantics as detailed in 174e2004d1865c201daf77494d50ab66527c12aa.

**Comment by hobodave** [comment]
Awesome, thanks @cheald. I just threw up another update to address the growing length of the `#instance_of?` checks.

**Comment by cheald** [comment]
0.5.0 released, and then rapidly followed up by 0.5.1 which fixed a regression I introduced during merging. Whoops.

**Pull request merged**
