### PR TITLE
add client.close to free resources

### LINKED ISSUE #38: Add a Manticore::Client#close method to free resources
It would be nice to have a way of freeing the resources associated with a manticore client whenever it is necessary after its creation:

```ruby
client = Manticore::Client.new(request_timeout: 5, connect_timeout: 5, socket_timeout: 5, pool_max: 10, pool_max_per_route: 2)
response = client.get("http://www.google.com/")
response.body
# ...eventually...
client.close
```

Since `@client` is a [CloseableHttpClient](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/CloseableHttpClient.html) this could be simply implemented as:

```ruby
class Manticore::Client
  def close
    @client.close if @client
  end
end
```

What do you think @cheald ?

### PR DESCRIPTION
**Pull request by jsvd**
fixes #38

### CODE REVIEW

**Comment by jsvd** [comment]
@cheald hi I was wondering if you could review this, since the lack of a "close" is creating a big fd leak in https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/306

**Comment by cheald** [comment]
So sorry I didn't get to it over the Thanksgiving weekend! I'm headed to bed at the moment but will review and close tomorrow morning. Thank you!

**Comment by jsvd** [comment]
oops I forgot about thanksgiving :D awesome, good night!

**Comment by cheald** [comment]
Merged and released 0.5.2.

**Pull request merged**
