### PR TITLE
CI: Use jruby-9.2.13.0

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR updates the CI matrix to use latest JRuby, **9.2.13.0**.

---

PS: I made a merge request in GitLab to the same effect. This is more of an informative PR.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Oh, yes, there is a 9.2.13.0 now.

**Comment by olleolleolle** [comment]
Failed with this, jdk8 seems unsupported. Going with 9, then

```
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"

Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2020-01-14
Expected feature release number in range of 9 to 15, but got: 8
```

**Comment by cheald** [comment]
It's been a while since I've looked at this, but it looks like JRuby 1.7 is deprecated, and the JDK landscape has changed a lot in the last few years, with new releases and licensing restrictions. I'd propose dropping 1.7 from the test matrix, and settling on a new set of JDKs to test against. Thoughts on the best set there?

**Comment by olleolleolle** [comment]
@cheald I took a look at https://www.jruby.org/download, and saw "stable release (2.3 support)" and "current release (2.5 support)".

We should only use those.

**Comment by olleolleolle** [comment]
I'll make an attempt, probably failing, seeing what CI says about the JDKs in use. Please don't pay any heed to falling bricks in this PR.

**Comment by cheald** [comment]
I went ahead and merged a new branch which updates the travisfile a bit. I dropped jruby-1.7 support, added jruby-9.1.17.0 and jruby-9.2.13.0, am now testing against openjdk 9 and 11, and fixed gem lookup issue caused by both the travisfile and Travis itself performing separate bundle steps. I think that covers what this PR did and then some.

**Comment by olleolleolle** [comment]
Perfect! Thanks for opening that up.

**Pull request closed without merging**
