### PR TITLE
Vendors jars instead of relying on jar-dependencies

### PR DESCRIPTION
**Pull request by fedenusy**

### CODE REVIEW

**Comment by cheald** [comment]
I actually started Manticore off by vendoring the jars, and then backed off of that approach in 0.5.0 because jar version conflicts are a *really* nasty issue in JRuby-land, and can produce all kinds of unexpected behavior or bugs (see https://github.com/cheald/manticore/issues/2 for example). The idea is that by letting jar-dependencies manage the deps, you will end up with more transparency about which jars are being used in a project, and jar-dependencies can manage version conflicts to ensure that only one jar gets loaded.

In short, if you were to use Manticore with another JRuby project that uses the Apache HTTPComponents, Commons-codec, or Commons-logging and Manticore was using vendored jars, you may end up with some extremely odd and hard-to-debug bugs. Given that jars can have transitive dependencies, not having this resolution could become a major issue down the road, hence the jar-dependencies route.

jar-dependencies does clearly have some kinks, but it's been *mostly* smooth outside of a few kinks with ruby-maven. What did the solution to your problem end up being - just vendoring the jars?

It would be somewhat awkward, but one option might be to ship a manticore gem (which uses jar-dependencies) and manticore-vendor (or something, which would have the vendored jars). Thoughts?

**Comment by fedenusy** [comment]
That makes sense. I agree with the sentiment, manticore *needs* something like jar-dependencies in the long run.

Today I spent all day trying to install manticore on different operating systems (Mac OS X, CoreOS, and Ubuntu) across different versions of JRuby 9000 (9.0.1.0, 9.0.4.0, and 9.0.5.0) while dealing with 3 different apps/Gemfiles.

**Not a single one** of my attempts to install manticore went smoothly. All issues stemmed from jar-dependencies and/or ruby-maven. Some of the errors were easily fixed; others weren't. **All errors stopped** after I started vendoring jars.

Clearly jar-dependencies and ruby-maven need some work. Based on mkristian's comments, it sounds like both projects should start working smoothly with the release of JRuby 9.1.

Regarding your proposed solution, cutting 2 different gems seems like a good workaround. A bit confusing, but it'll do the trick.

A more elegant solution may involve something like this:

```
if Kernel.repond_to?(:require_jars)
  # require_jars
else
  # require_relative
end
```

I'm not sure whether the approach above is technically feasible since I've never worked with jar-dependencies before. What's nice is we remove the confusion that'll come from cutting 2 different gems. And if you're already using jar-dependencies, then great, you get jar dependency resolution. Do you think this would be possible?

If that approach is too complex, I think the 2-gem approach would be fine.

**Comment by cheald** [comment]
I'm wondering if I might be able to help out jar-dependencies a bit and smooth out some of those issues, with some additional metadata in the Manticore gem. I'd like to explore that route first. I'm going to spend some time with some Docker containers and see if I can come up with a consistent failure scenario, and work backwards from there. Can you give me an exhaustive enumeration of the OS/Java version (including JDK or JRE)/Ruby installs you tried? I'll try to come up with a test matrix of my own, as well.

Vendored jars remain an option, but I'd like to exhaust the jar-deps route first before going down that path.

**Comment by cheald** [comment]
Okay, starting clean, I'm having issues just `bundle`ing a fresh Manticore source tree - something has definitely changed. This might be as easy as a version constraint on the relevant tools. :)

**Comment by fedenusy** [comment]
I base my containers off 2 different images:

- FROM coreos/apache:latest
- [FROM phusion/baseimage:0.9.18](https://github.com/phusion/baseimage-docker) -- Ubuntu 14.04 with some extras.

Both containers run openjdk-8-jre-headless.

I use rvm to install JRuby, and if memory serves I tried JRuby 9.0.1.0, 9.0.4.0, and 9.0.5.0 on both container types.

A lot of my fixes went something like this:

- `bundle install` -> error
- `gem install ruby-maven` then `bundle install` -> error
- `gem install ruby-maven jar-dependencies` then `bundle install` -> success

Sometimes, a seemingly arbitrary change in the order of operations would fix the issue. In one case I had to do something like `bundle install` -> `gem uninstall` -> `bundle install` before manticore would start working correctly. Those were the nicer install experiences.

The worst install experience was the one described [in this comment](https://github.com/cheald/manticore/issues/46#issuecomment-200486260). The only solution I found for that error involved vendoring jars; this issue *definitely* happened in Ubuntu + JRuby 9.0.1.0, and it may have happened in other environments (though I forget the other combinations).

**Comment by cheald** [comment]
Excellent, thank you. I've got the error replicated and I'm digging into what's going on. I *think* at this point that it's a problem with the Maven Polyglot extensions not being loaded, but I'm not positive yet.

I'm hoping that I can end up using `lock_jars` provided by jar-deps to completely circumvent the Maven dependency while allowing jar-deps to do its thing. Will see when I get this working!

**Comment by fedenusy** [comment]
Great, thanks for digging into this!

In case it helps there was also my local machine (`Mac OS X 10.11.3`) which runs `Java(TM) SE Runtime Environment (build 1.8.0_73-b02)`, rvm, and jruby-9.0.1.0. This one was also fixed with arbitrary combinations of `gem install` / `gem install` / `bundle install`.

**Comment by cheald** [comment]
Okay, this is *super* weird. After blowing away my ~/.m2 directory and reinstalling JRuby-9.0.4.0, the issue has completely disappeared. I can't replicate it at all.

At this point I think it's pretty clear that we need to get jar-deps out of the runtime pipeline, at least until it settles down. :)

I've re-vendored the jars (similar to what you've done here), but I'm using jar-deps to manage them. This will allow jbundler to detect version issues and allow the user to make choices in the case of conflicts. Check out the `vendored-jars` branch and see if that works for you. If so, then that'll become 0.6.0.

**Comment by fedenusy** [comment]
`vendored-jars` worked well. Feel free to close this PR and release 0.6.0 :)

Thanks for the help Chris!

**Comment by mkristian** [comment]
yes, ruby-maven is broken on jruby-9.0.5.0 and with it the jar-dependencies.

if you want to vendor jar please use the jar-dependencies feature to do so, i.e. declare you jar dependencies inside the gemspec, only then you can us the gem in frameworks like gradle and maven with its jar + gem dependencies

jrjackson is a nightmare with its vendored jars when I want to use it with https://github.com/lookout/leafy/tree/master/leafy-metrics which pulls in its version of the jackson libraries.

**Comment by mkristian** [comment]
the problem here is: https://github.com/jruby/jruby/issues/3676 - not using jruby-9.0.5.0 should solve the issue with maven-polyglot

**Comment by fedenusy** [comment]
@mkristian fyi the error also happens in JRuby 9.0.1.0 and 9.0.4.0. Check out the logs from [this comment](https://github.com/cheald/manticore/issues/46#issuecomment-200486260), which show the error happening in JRuby 9.0.4.0.

**Comment by mkristian** [comment]
@fedenusy I see it is something else then. is there any reproducible case ?

**Comment by cheald** [comment]
@fedenusy: I built the following Dockerfile and it installed cleanly for me:

~~~
FROM phusion/baseimage:0.9.18
RUN apt-get update
RUN apt-get install git openjdk-7-jre build-essential -y
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
RUN ~/.rbenv/bin/rbenv install jruby-9.0.4.0

# docker build .
# docker run -t -i <image_id> /bin/bash
# ~/.rbenv/versions/jruby-9.0.4.0/bin/gem install manticore -v '0.5.5'
~~~

Can you suggest a modification to the Dockerfile that reproduces the issue?

**Comment by cheald** [comment]
@mkristian Here's a Dockerfile which exhibits the issue:

~~~
FROM phusion/baseimage:0.9.18
RUN add-apt-repository ppa:openjdk-r/ppa -y
RUN apt-get update
RUN apt-get install git build-essential openjdk-8-jre-headless -y
RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
RUN curl -sSL https://get.rvm.io | bash
RUN /bin/bash -l -c "rvm install jruby-9.0.4.0"

# Build the image:
#   docker build . -t manticore/jruby-9040-jre-8-rvm
# To see it fail:
#   docker run -t manticore/jruby-9040-jre-8-rvm /bin/bash -l -c "gem install manticore -v '0.5.5'"
# For a login shell to poke about in:
#   docker run -i -t manticore/jruby-9040-jre-8-rvm /bin/bash -l
~~~

This works on JRuby-1.7.19 in the same env, but fails on JRuby 9.0.4.0 and JRuby-1.7.23

## Jruby 1.7.19 - pass
```
root@5c079706e09a:/# rvm use jruby-1.7.19
Using /usr/local/rvm/gems/jruby-1.7.19
root@5c079706e09a:/# gem install manticore -v '0.5.5'
Fetching: manticore-0.5.5-java.gem (100%)
Successfully installed manticore-0.5.5-java
1 gem installed
```

## Jruby 9.0.4.0 - fail
```
root@5c079706e09a:/# rvm use jruby-9.0.4.0
Using /usr/local/rvm/gems/jruby-9.0.4.0
root@5c079706e09a:/# gem install manticore -v '0.5.5'
  jar dependencies for manticore-0.5.5-java.gemspec . . .
Warning: JAVA_HOME environment variable is not set.
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/local/rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/usr/local/rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/jars/jar_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/local/rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/jars/jar_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /usr/local/rvm/gems/jruby-9.0.4.0/gems/manticore-0.5.5-java/deps.lst
```
## Jruby 1.7.23 - fail
```
root@5c079706e09a:/# rvm use jruby-1.7.23
Using /usr/local/rvm/gems/jruby-1.7.23
root@5c079706e09a:/# gem install manticore -v '0.5.5'
Fetching: manticore-0.5.5-java.gem (100%)
  jar dependencies for manticore-0.5.5-java.gemspec . . .
Installing gem 'ruby-maven' . . .
Fetching: ruby-maven-libs-3.3.3.gem (100%)
Successfully installed ruby-maven-libs-3.3.3
Fetching: ruby-maven-3.3.10.gem (100%)
Successfully installed ruby-maven-3.3.10

using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

Warning: JAVA_HOME environment variable is not set.
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/local/rvm/rubies/jruby-1.7.23/lib/ruby/shared/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/usr/local/rvm/rubies/jruby-1.7.23/lib/ruby/shared/jars/gemspec_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/local/rvm/rubies/jruby-1.7.23/lib/ruby/shared/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /usr/local/rvm/gems/jruby-1.7.23/gems/manticore-0.5.5-java/deps.lst
```

**Comment by cheald** [comment]
Further experimentation with this Dockerfile shows that it works on 1.7.19 and 1.7.20, but breaks on 1.7.21 onwards.

**Comment by mkristian** [comment]
@cheald thanks for digging. yes, rvm caused problems in the past. let's see if I can get some more inside

**Comment by mkristian** [comment]
@cheald running docker made me run out of diskspace - need more time :(

but created a PR for jrjackson to use jar-dependencies but vendor those jars - the jar declarations inside the gemspec is more important then install those jars on install time: https://github.com/guyboertje/jrjackson/pull/52

maybe this is something for manticore as well or until the RVM and ruby-maven issue is fixed.

**Comment by mkristian** [comment]
so a short update on this, the actual error has to do with the ssl certificate from repo.maven.apache.org
```
cat .m2/repository/io/takari/polyglot/polyglot-ruby/0.1.11/polyglot-ruby-0.1.11.pom.lastUpdated
#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Wed Apr 06 08:09:42 UTC 2016
@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1459930182263
https\://repo.maven.apache.org/maven2/.error=Could not transfer artifact io.takari.polyglot\:polyglot-ruby\:pom\:0.1.11 from/to central (https\://repo.maven.apache.org/maven2)\: java.lang.RuntimeException\: Unexpected error\: java.security.InvalidAlgorithmParameterException\: the trustAnchors parameter must be non-empty
```
so it might be not a rvm but jdk/jre problem

**Comment by mkristian** [comment]
fixing the java installation is done:
```
update-ca-certificates -f
```

on building the container I have following warnings:
```
Setting up ca-certificates-java (20130815ubuntu1) ...
/var/lib/dpkg/info/ca-certificates-java.postinst: line 53: java: command not found
/var/lib/dpkg/info/ca-certificates-java.postinst: line 66: java: command not found
done.
Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....
/etc/ca-certificates/update.d/jks-keystore: 82: /etc/ca-certificates/update.d/jks-keystore: java: not found
```
i.e. ubuntu has no java and can not update the certificates and the openjdk installation comes after this.

looks more the openjdk debian package has a bug or something in this direction.

BTW jruby-openssl does use the java keystore in certain situations but other java libraries might depend on those missing ca-certs - so it is always advisable to keep those in sync in mixed jruby/java application.

**Comment by fedenusy** [comment]
@mkristian's suggestion fixes the issue. Guess the problem is with java itself.

@cheald feel free to delete the `vendored-jars` branch, since jar-dependencies is not at fault here.

**Comment by cheald** [comment]
Hm. Okay, good to know. I'll see if I can come up with a fix-it scenario for this particular problem.

**Comment by mkristian** [comment]
@cheald BTW jrjackson did switch to jar-dependencies with vendored jars. on jar-dependencies side I will improve the error message a bit if possible.

**Comment by cheald** [comment]
I've decided to release 0.6.0 with vendored jars managed by jar-dependencies. I feel like it's probably the smoothest path forward for now, given that jar-deps can manage conflicts and this will bypass the Maven cert issues.

**Pull request closed without merging**
